"use strict";
// Conditional Tests: Write a series of conditional tests. Print a statement describing each test and your prediction for the results of each test. Your code should look something like this:
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car != 'subaru'? I predict True.");
console.log(car != 'subaru');
let car1 = 'Honda City';
console.log("Is car1 == 'Honda City'? I predict True.");
console.log(car1 == 'Honda City');
console.log("Is car1 != 'Honda City'? I predict True.");
console.log(car1 != 'Honda City');
let car2 = 'Civic';
console.log("Is car2 == 'Civic'? I predict True.");
console.log(car2 == 'Civic');
console.log("Is car2 != 'Civic'? I predict True.");
console.log(car2 != 'Civic');
let car3 = 'Supra';
console.log("Is car3 == 'Supra'? I predict True.");
console.log(car3 == 'Supra');
console.log("Is car3 != 'Supra'? I predict True.");
console.log(car3 != 'Supra');
let car4 = 'BMW';
console.log("Is car4 == 'BMW'? I predict True.");
console.log(car4 == 'BMW');
console.log("Is car4 != 'BMW'? I predict True.");
console.log(car4 != 'BMW');
